### ISSUE TITLE
Week4

### ISSUE THREAD

**Issue by Aman748** [zhamri/STIW3054-RT-Programming#3]
package Week_04;

class TestSleep2 implements Runnable {

    @Override
    public void run() {
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());
            if(Thread.currentThread().getName().equals("Three"))
                System.out.println("*********");
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new TestSleep2(), "One");
        Thread t2 = new Thread(new TestSleep2(), "TWO");
        Thread t3 = new Thread(new TestSleep2(), "Three");
        t1.start();
        t1.sleep(1000);
        t2.start();
        t2.sleep(1000);
        t3.start();
    }
}

**Comment by syeel** [comment]
Solving this issue with usage of **synchronized()**, **wait()** and **notifyAll()**

``` java
package Week_04;

public class TestSleep2 {

    volatile int status=1;
    public static void main(String[] args) {

        TestSleep2 ts2 = new TestSleep2();

        PrintOne t1 = new PrintOne(ts2);
        PrintTwo t2 = new PrintTwo(ts2);
        PrintThree t3 = new PrintThree(ts2);

        t1.start();
        t2.start();
        t3.start();
    }
}
```
``` java
class PrintOne extends Thread{
    TestSleep2 ts2;

    PrintOne(TestSleep2 ts2){
        this.ts2 = ts2;
    }

    @Override
    public void run() {
        try{
            synchronized (ts2) {
                for (int i = 0; i < 3; i++) {
                    while(ts2.status!=1){
                        ts2.wait();
                    }
                    System.out.println("One");
                    ts2.status = 2;
                    ts2.notifyAll();
                }
            }
        }catch (Exception e) {
            System.out.println("Exception 1 :"+e.getMessage());
        }
    }
}
```

```java
class PrintTwo extends Thread{
    TestSleep2 ts2;

    PrintTwo(TestSleep2 ts2){
        this.ts2 = ts2;
    }

    @Override
    public void run() {
        try{
            synchronized (ts2) {
                for (int i = 0; i < 3; i++) {
                    while(ts2.status!=2){
                        ts2.wait();
                    }
                    System.out.println("Two");
                    ts2.status = 3;
                    ts2.notifyAll();
                }
            }
        }catch (Exception e) {
            System.out.println("Exception 1 :"+e.getMessage());
        }
    }
}
```

```java
class PrintThree extends Thread{
    TestSleep2 ts2;

    PrintThree(TestSleep2 ts2){
        this.ts2 = ts2;
    }

    @Override
    public void run() {
        try{
            synchronized (ts2) {
                for (int i = 0; i < 3; i++) {
                    while(ts2.status!=3){
                        ts2.wait();
                    }
                    System.out.println("Three");
                    System.out.println("xxxxxxxxxx");
                    ts2.status = 1;
                    ts2.notifyAll();
                }
            }
        }catch (Exception e) {
            System.out.println("Exception 1 :"+e.getMessage());
        }
    }
}
```

**Output**
![output](https://user-images.githubusercontent.com/31965373/31315841-0326ff34-ac53-11e7-9c25-d5a27a43631c.JPG)

**Comment by TEELIHONG** [comment]
package Week_04;

class TestSleep2 implements Runnable {

    @Override
    public void run() {
    
        for (int i = 1; i <=5 ; i++) {
             System.out.println(Thread.currentThread().getName());
             if(Thread.currentThread().getName().equals("Three"))
                  System.out.println("xxxxxxxxxx");          
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);                             
            } catch (Exception e) {
                System.out.println(e);
            }          
        }      
    }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new TestSleep2(),"One"); 
        t1.setPriority(Thread.MAX_PRIORITY);               
        Thread t2 = new Thread(new TestSleep2(),"TWO"); 
        t2.setPriority(Thread.NORM_PRIORITY);
        Thread t3 = new Thread(new TestSleep2(),"Three");
        t3.setPriority(Thread.MIN_PRIORITY);
        
        t1.start();
        t2.start();
        t3.start();
        
        t1.join();
        t2.join();
        t3.join();

    }    
}

![op](https://user-images.githubusercontent.com/31922731/31399442-ddb97fce-ae1e-11e7-9e4b-b12e1649c8dd.PNG)

**Comment by Tamilarasi95** [comment]
package week_04;



class TestSleep2 implements Runnable {

@Override
public void run() {
    for (int i = 1; i <= 5; i++) {
        System.out.println(Thread.currentThread().getName());
        if(Thread.currentThread().getName().equals("THREE"))
            System.out.println("xxxxxxxxxx");
        try {
            // thread to sleep for 5000 milliseconds
            Thread.sleep(5000);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}

public static void main(String[] args) throws Exception {

    Thread t1 = new Thread(new TestSleep2(), "ONE");
    Thread t2 = new Thread(new TestSleep2(), "TWO");
    Thread t3 = new Thread(new TestSleep2(), "THREE");
    
     t1.setName("ONE");
     t2.setName("TWO");
     t3.setName("THREE");
      
    t1.start();
    Thread.sleep(1000);
    t2.start(); 
    Thread.sleep(1000);
    t3.start();
    Thread.sleep(1000);
    
   
}
}

![image](https://user-images.githubusercontent.com/31919219/31554798-496e37c4-b071-11e7-8fd9-1af947bfe34a.png)

**Comment by TeeMeiYit** [comment]
package Week_04;

class TestSleep2 implements Runnable {

    @Override
    public void run() {
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());   
            if(Thread.currentThread().getName().equals("Three")){
                System.out.println("*******");
            }
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);
                
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new TestSleep2(), "One");
        Thread t2 = new Thread(new TestSleep2(), "TWO");
        Thread t3 = new Thread(new TestSleep2(), "Three");

        t1.start();
        try{
            t1.join(1000);
        }catch (Exception e){

        }
        t2.start();
        try{
            t2.join(2000);
        }catch (Exception e){

        }
        t3.start();
        try{
            t3.join(3000);
        }catch (Exception e){

        }
}
}
![screenshot 141](https://user-images.githubusercontent.com/31920062/31584069-6dfd884c-b1d9-11e7-836b-5de2d79b60c5.png)

**Comment by Jiayin328** [comment]
package Week_04;

class TestSleep2 implements Runnable {

    @Override
    public void run() {
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());
            if (Thread.currentThread().getName().equalsIgnoreCase("Three")) {
                    System.out.println("****************");
            }
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);
            } catch (Exception e) {
                System.out.println(e);
            }
            
        }
    }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new TestSleep2(), "One");
        Thread t2 = new Thread(new TestSleep2(), "Two");
        Thread t3 = new Thread(new TestSleep2(), "Three");
        
        t1.start();
        t1.join(1000);
        
        t2.start();
        t2.join(2000);
        
        t3.start();
        t3.join(3000);
    }
}

![image](https://user-images.githubusercontent.com/31919741/31600599-a5d28b5e-b289-11e7-8e4a-63519be05296.png)

**Comment by Meenanbeega96** [comment]
package Week_04;

    class TestSleep2 implements Runnable {
  
     public static void main(String[] args) throws Exception {

    Thread t1 = new Thread(new TestSleep2(), "ONE");
    Thread t2 = new Thread(new TestSleep2(), "TWO");
    Thread t3 = new Thread(new TestSleep2(), "THREE");
    
    t1.start();
    Thread.sleep(1000);
  
    t2.start();
    Thread.sleep(1000);
    
    t3.start();
    Thread.sleep(1000);
}
    
    @Override
    public void run() {
    for (int i = 1; i <= 5; i++) {
        System.out.println(Thread.currentThread().getName());
        if (Thread.currentThread().getName().equalsIgnoreCase("Three")) {
                System.out.println("###############");
        }
        try {
            // thread to sleep for 5000 milliseconds
            Thread.sleep(5000);
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
 }   
     
}

![image](https://user-images.githubusercontent.com/31919632/31613398-95067b60-b2b5-11e7-831f-376418cca1f6.png)

**Comment by bad96** [comment]
package Week_04;

class TestSleep2 implements Runnable {

    @Override
    public void run() {
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());
            try {
                Thread.sleep(5000);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new TestSleep2(), "One");
        Thread t2 = new Thread(new TestSleep2(), "TWO");
        Thread t3 = new Thread(new TestSleep2(), "Three \n************");
        t1.setPriority(t1.MAX_PRIORITY);
        t1.start();
        t1.sleep(1000);
        t2.start();
        t2.sleep(1000);
        t3.start();
    }
}

**Comment by NurAinAmanina** [comment]
package assignment2;

class testsleep implements Runnable {

    @Override
    public void run() {
        
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());
            
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);
            } catch (Exception e) {
                System.out.println(e);
                
            }
        }
        }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new testsleep(), "ONE");
        Thread t2 = new Thread(new testsleep(), "TWO");
        Thread t3 = new Thread(new testsleep(), "THREE \n************");
        
        t1.start();
        t1.sleep(200);
        t2.start();
        t1.sleep(200);
        t3.start();
        t1.sleep(200);
        

    }
}

**Comment by nurulsyafawani** [comment]
//package Week_04;

class TestSleep2 implements Runnable {

    @Override
    public void run() {
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());
            if (Thread.currentThread().getName().equals("Three")){
                System.out.println("xxxxxxxxxxxxxxxxxxxx");
            }
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    public static void main(String[] args) throws Exception {

        Thread t1 = new Thread(new TestSleep2(), "One");
        Thread t2 = new Thread(new TestSleep2(), "TWO");
        Thread t3 = new Thread(new TestSleep2(), "Three");
        t1.start();
        Thread.sleep(50);
        t2.start();
        Thread.sleep(50);
        t3.start();
        
    }
}
![issue4](https://user-images.githubusercontent.com/32368173/31762688-8e16a8c6-b4ee-11e7-817d-82aaf3612a0a.PNG)

**Comment by MarJr** [comment]
`class TestSleep2 implements Runnable {
    
    @Override
    public void run() {
        for (int i = 1; i <= 5; i++) {
            System.out.println(Thread.currentThread().getName());
            Thread.currentThread().getName();
            try {
                // thread to sleep for 5000 milliseconds
                Thread.sleep(5000);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
    
    public static void main(String[] args) throws Exception {
        
        Thread t1 = new Thread(new TestSleep2(), "One");
        Thread t2 = new Thread(new TestSleep2(), "TWO");
        Thread t3 = new Thread(new TestSleep2(), "Three \n*********");
        
        t1.start();
        Thread.sleep(500);
        t2.start();
        Thread.sleep(500);
        t3.start();
        
    }
}`

**Comment by amsyarrazak** [comment]
class Issues5 implements Runnable {

@Override
public void run() {
    for (int i = 1; i <= 5; i++) {
        System.out.println(Thread.currentThread().getName());
        if(Thread.currentThread().getName().equals("Three"))
            System.out.println("*********");
        try {
            // thread to sleep for 5000 milliseconds
            Thread.sleep(5000);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}

public static void main(String[] args) throws Exception {

    Thread t1 = new Thread(new Issues5(), "One");
    Thread t2 = new Thread(new Issues5(), "Two");
    Thread t3 = new Thread(new Issues5(), "Three");
    t1.start();
    t1.sleep(1000);
    t2.start();
    t2.sleep(1000);
    t3.start();
}
}



![screenshot 131](https://user-images.githubusercontent.com/32288017/32723474-8be7a9c4-c8a8-11e7-8d37-da159a29411c.png)

**Comment by AminAsyraf94** [comment]
package week04;

class TestSleep2 implements Runnable {

@Override
public void run() {
    for (int i = 1; i <= 5; i++) {
        System.out.println(Thread.currentThread().getName());
        if(Thread.currentThread().getName().equals("THREE"))
            System.out.println("*********");
        try {
            // thread to sleep for 5000 milliseconds
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            System.out.println(e);
        }
    }
}

public static void main(String[] args) throws Exception {

    Thread t1 = new Thread(new TestSleep2(), "ONE");
    Thread t2 = new Thread(new TestSleep2(), "TWO");
    Thread t3 = new Thread(new TestSleep2(), "THREE");
    t1.start();
    Thread.sleep(1000);
    t2.start();
    Thread.sleep(1000);
    t3.start();
}
}
